TSPNAgncyWeb/Controllers/FaxController.cs
using com.rti.tailspinnew.Models;
using com.rti.tailspinnew.Models.WcfAppService;
using com.rti.tailspinnew.web.Models.Common;
using System;
using System.Collections.Generic;
using System.IO;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;

namespace com.rti.tailspinnew.web
{
	public class FaxController : MyController
	{
		private List<localInbox> files = new List<localInbox>();

		public FaxController()
		{
		}

		public static string CreateFileFromByteArray(byte[] bytFileContents, string strFileName)
		{
			string str = string.Concat(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "\\TSPN");
			string str1 = string.Concat(str, "\\", strFileName);
			try
			{
				byte[] numArray = bytFileContents;
				if (!System.IO.File.Exists(str1))
				{
					FileStream fileStream = new FileStream(str1, FileMode.Create, FileAccess.Write);
					fileStream.Write(numArray, 0, (int)numArray.Length);
					fileStream.Close();
					fileStream.Dispose();
				}
			}
			catch (Exception exception)
			{
			}
			return str1;
		}

		public ActionResult FaxList()
		{
			List<localInbox> localInboxes = new List<localInbox>();
			localInboxes = WebSessionManager.getRejectedInboxList((int)base.Session["usertoken"], (int)base.Session["agentAppId"], (int)base.Session["agencyAppId"]);
			return base.View(localInboxes);
		}

		public static byte[] GetFileContents(string fileName)
		{
			byte[] numArray = null;
			try
			{
				FileStream fileStream = new FileStream(fileName, FileMode.Open, FileAccess.Read);
				try
				{
					try
					{
						BinaryReader binaryReader = new BinaryReader(fileStream);
						long length = (new FileInfo(fileName)).Length;
						numArray = binaryReader.ReadBytes((int)length);
						binaryReader.Close();
					}
					catch (Exception exception)
					{
					}
				}
				finally
				{
					fileStream.Close();
					fileStream.Dispose();
				}
			}
			catch (Exception exception1)
			{
			}
			return numArray;
		}

		public ActionResult NewFax()
		{
			return base.View();
		}

		protected override void OnActionExecuted(ActionExecutedContext filterContext)
		{
			ClearCache.ClearAllCache();
			base.OnActionExecuted(filterContext);
		}

		protected override void OnActionExecuting(ActionExecutingContext filterContext)
		{
			if (!System.Web.HttpContext.Current.User.Identity.IsAuthenticated || base.Session["UserRole"] == null)
			{
				filterContext.Result = new RedirectResult(base.Url.Action("LogOn", "Account"));
			}
			base.OnActionExecuting(filterContext);
		}

		public ActionResult PDFFile(int Id)
		{
			MemoryStream memoryStream = new MemoryStream();
			List<string> pDFFileContentsByIndex = WebSessionManager.getPDFFileContentsByIndex(Id);
			if (pDFFileContentsByIndex.Count > 0)
			{
				FileInfo fileInfo = new FileInfo(pDFFileContentsByIndex[0]);
				byte[] fileContents = FaxController.GetFileContents(fileInfo.FullName);
				memoryStream.Write(fileContents, 0, (int)fileContents.Length);
				memoryStream.Position = (long)0;
				base.HttpContext.Response.AddHeader("content-disposition", string.Concat("attachment; filename=", fileInfo.Name));
			}
			return new FileStreamResult(memoryStream, "application/pdf");
		}

		public ActionResult ShowPDF(int fileID)
		{
			return null;
		}
	}
}

TSPNAgncyWeb/Views/Shared/AgencyLeftPane.cshtml
<table bgcolor="#E3F1BD" cellpadding="0px" cellspacing="0px" width="210px"  >
<tr class="LeftPaneHLink">
<td >
@Html.ActionLink("Agency Profile", "Home")
</td>
</tr>

<tr class="LeftPaneHLink">
<td style="padding-left:20px">
@Html.ActionLink("Manage Agency Users (links to H8 – list of agency users)", "Home")

</td>
</tr>
<tr class="LeftPaneHLink">
<td style="padding-left:20px">
@Html.ActionLink("My Profile", "Home")

</td>
</tr>
<tr class="LeftPaneHLink">
<td style="padding-left:20px">
@Html.ActionLink("Create Agency User", "Home")

</td>
</tr>
<tr class="LeftPaneHLink">
<td style="padding-left:20px">
@Html.ActionLink("Report", "Home")

</td>
</tr>
</table>

TSPNAgncyWeb/Views/Shared/HelpLeftPane.cshtml
<table bgcolor="#E3F1BD" cellpadding="0px" cellspacing="0px" width="210px"  >
<tr class="LeftPaneHLink">
<td >
@Html.ActionLink("Contact Support", "Home")
</td>
</tr>
<tr class="LeftPaneHLink">
<td style="color:#CC6666">
@Html.ActionLink("About", "Applications")
</td>
</tr>
</table>

TSPNAgncyWeb/Views/Shared/LeftPane.cshtml
<table bgcolor="#ECF3C8" cellpadding="0px" cellspacing="0px" width="210px"  >
<tr class="LeftPaneHLink">@*bgcolor="#E3F1BD"*@
<td >
@Html.ActionLink("Create New Application", "TCAF", "CAF")
</td>
</tr>
<tr class="LeftPaneHLink">
<td style="color:#CC6666">
@Html.Label("lblHeading","Applications")
</td>
</tr>
<tr class="LeftPaneHLink">
<td style="padding-left:20px">
@Html.ActionLink("To be submitted (NEW)", "CAFList","CAF")

</td>
</tr>
<tr class="LeftPaneHLink">
<td style="padding-left:20px">
@Html.ActionLink("Incomplete (INCOMPLETE)", "CAFList", "CAF")

</td>
</tr>
<tr class="LeftPaneHLink">
<td style="padding-left:20px">
@Html.ActionLink("Submitted Applications", "CAFList", "CAF")

</td>
</tr>
<tr class="LeftPaneHLink">
<td style="padding-left:20px">
@Html.ActionLink("View by Children", "CAFList", "CAF")

</td>
</tr>
<tr class="LeftPaneHLink">
<td style="padding-left:20px">
@Html.ActionLink("View applications by Camp", "CAFList", "CAF")

</td>
</tr>
<tr class="LeftPaneHLink">
<td style="padding-left:20px">
@Html.ActionLink("View My Submissions", "CAFList", "CAF")
</td>
</tr>
<tr class="LeftPaneHLink">
<td style="padding-left:20px" >
@Html.ActionLink("View All Submissions", "CAFList", "CAF")
</td>
</tr>
<tr class="LeftPaneHLink">
<td>
@Html.ActionLink("Rejected Faxes", "FaxList","Fax")
</td>
</tr>
</table>

TSPNAgncyWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>My MVC Application</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>

TSPNAgncyWeb/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}